spring:
  application:
    name: config-service




  cloud:
    discovery:
      enabled:true

    config:
      server:
        git:
          uri: C:/Users/user/Desktop/s4/micro serv/prjx2/ecom-ms-spring-boot-app/config-repo

server:
  port: 9999
